### ISSUE TITLE
能更新一波版本吗？

### ISSUE THREAD

**Issue by roshanman** [IamAlasca/XimalayaSDK#1]
有几个问题请教一下
1. 这个仓库还维护吗，什么时候能更新一下版本和官网保持一致
2. podspec文件里面的subspec是你们定制的吗？
是否可以改成依赖，不然和我们工程已有的FMDB，MBProgressHUD会有冲突

**Comment by IamAlasca** [comment]
您好，最新版本对FMDB和MBProgressHUD的依赖已经去除，后续会及时跟喜马拉雅官网同步更新。

**Comment by IamAlasca** [comment]
您好，最新版本对FMDB和MBProgressHUD的依赖已经去除，后续会及时跟喜马拉雅官网同步更新。
